"""
scripts/producer.py — synthetic transaction producer.

Generates Faker-backed Transaction protobuf messages and publishes them to
the `transactions` Kafka topic. Used for local dev, smoke tests, and
load tests.

Tuning notes:
  - Single producer thread saturates ~10K msgs/sec with linger.ms=5.
  - To hit 50K/sec for benchmarking, run multiple producers in parallel
    or use scripts/load_test.py (Locust).
  - acks=1 (leader-only) trades a small durability risk for ~3x throughput
    versus acks=all. For benchmark/dev only — never use acks=1 in prod.

Usage:
  python scripts/producer.py --rate 5000 --duration 60
  python scripts/producer.py --rate 5000 --fraud-rate 0.05  # 5% fraud-flavored tx
"""

from __future__ import annotations

import argparse
import logging
import os
import random
import signal
import sys
import time
import uuid
from datetime import datetime, timezone

# protobuf stubs are generated by `python -m grpc_tools.protoc` — see ml_server/Dockerfile.
# For local script use, generate them once into scripts/_generated/ first:
#   python -m grpc_tools.protoc -Iproto --python_out=scripts/_generated proto/fraud.proto
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "_generated"))
import fraud_pb2  # noqa: E402

from confluent_kafka import Producer  # noqa: E402
from faker import Faker  # noqa: E402

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] producer: %(message)s",
)
log = logging.getLogger(__name__)

faker = Faker()

# A small fixed user pool — keeps Redis cache hit rates realistic.
# Real prod has millions of users; for local dev, 10K is plenty.
USER_POOL = [f"user-{i:06d}" for i in range(10_000)]
MERCHANT_POOL = [f"merchant-{i:04d}" for i in range(1_000)]
COUNTRIES = ["US", "GB", "DE", "FR", "JP", "CA", "AU", "BR", "IN"]
SUSPICIOUS_COUNTRIES = ["NG", "RO", "RU"]  # higher fraud base rate in synthetic data


def make_transaction(fraud_flavor: bool = False) -> fraud_pb2.Transaction:
    """
    Build a single Transaction message.

    `fraud_flavor=True` biases toward features the rule engine and model
    will both flag: large amounts, unusual countries, off-hours timestamps.
    Useful for verifying DLQ routing end-to-end.
    """
    tx = fraud_pb2.Transaction()
    tx.tx_id        = str(uuid.uuid4())
    tx.user_id      = random.choice(USER_POOL)
    tx.merchant_id  = random.choice(MERCHANT_POOL)

    if fraud_flavor:
        tx.amount   = round(random.uniform(2_000, 9_999), 2)  # large
        tx.country  = random.choice(SUSPICIOUS_COUNTRIES)
    else:
        tx.amount   = round(random.uniform(5, 500), 2)        # normal
        tx.country  = random.choice(COUNTRIES)

    tx.currency     = "USD"
    tx.timestamp_ms = int(datetime.now(timezone.utc).timestamp() * 1000)
    # First 6 of card number — never the full PAN (would put us in PCI scope).
    tx.card_bin     = f"{random.randint(400000, 499999)}"
    tx.device_id    = faker.uuid4()
    tx.ip_address   = faker.ipv4()
    tx.method       = fraud_pb2.Transaction.PaymentMethod.CARD
    return tx


def delivery_report(err, msg) -> None:
    if err is not None:
        log.warning("delivery failed: %s", err)


def main() -> int:
    parser = argparse.ArgumentParser(description="Synthetic Kafka transaction producer")
    parser.add_argument("--brokers", default=os.environ.get("KAFKA_BROKERS", "localhost:9092"))
    parser.add_argument("--topic",   default=os.environ.get("KAFKA_INPUT_TOPIC", "transactions"))
    parser.add_argument("--rate", type=int, default=1000, help="Messages per second target")
    parser.add_argument("--duration", type=int, default=0, help="Seconds to run (0 = forever)")
    parser.add_argument("--fraud-rate", type=float, default=0.01, help="Fraction of fraud-flavored tx")
    args = parser.parse_args()

    producer = Producer({
        "bootstrap.servers": args.brokers,
        # linger.ms=5 batches small bursts without adding meaningful latency.
        # batch.size up so we don't fragment.
        "linger.ms":       5,
        "batch.size":      32 * 1024,
        "acks":            1,        # leader-only — bench/dev. Use "all" in prod.
        "compression.type": "lz4",
    })

    # Graceful shutdown. Ctrl-C → flush in flight messages, then exit.
    stop = {"flag": False}
    def _sig(_signo, _frame):
        log.info("signal received, flushing producer...")
        stop["flag"] = True
    signal.signal(signal.SIGINT, _sig)
    signal.signal(signal.SIGTERM, _sig)

    interval = 1.0 / args.rate
    start = time.time()
    sent = 0

    log.info("producing to %s @ %d msg/s (fraud_rate=%.3f)",
             args.topic, args.rate, args.fraud_rate)

    while not stop["flag"]:
        if args.duration and time.time() - start >= args.duration:
            break

        is_fraud = random.random() < args.fraud_rate
        tx = make_transaction(fraud_flavor=is_fraud)
        producer.produce(
            topic=args.topic,
            key=tx.user_id.encode("utf-8"),  # key by user_id → same partition for ordering
            value=tx.SerializeToString(),
            on_delivery=delivery_report,
        )
        sent += 1

        # Drain delivery callbacks every batch so the queue doesn't fill up.
        if sent % 1000 == 0:
            producer.poll(0)
            elapsed = time.time() - start
            log.info("sent=%d, elapsed=%.1fs, eff_rate=%.0f/s",
                     sent, elapsed, sent / max(elapsed, 1e-9))

        # Crude rate limiter. For higher rates we'd switch to a token bucket.
        time.sleep(interval)

    producer.flush(timeout=10)
    log.info("done. total sent=%d", sent)
    return 0


if __name__ == "__main__":
    sys.exit(main())
